from . import (
    audit,
    auth,
    billing,
    chat,
    domains,
    issues,
    knowledge,
    members,
    orgs,
    pentests,
    pr_reviews,
    repositories,
    tokens,
    webhooks,
)

ALL_ROUTERS = [
    auth.router,
    orgs.router,
    members.router,
    repositories.router,
    domains.router,
    pentests.router,
    pentests.schedules_router,
    issues.router,
    pr_reviews.router,
    pr_reviews.webhook_router,
    knowledge.router,
    chat.router,
    tokens.router,
    webhooks.router,
    billing.router,
    audit.router,
]
